title: "Allocated Resources"
description: ""
domain: cfsgoncalves.github.io      
url: https://cfsgoncalves.github.io 
baseurl: ""

header_pages:
  - index.md
  - support.md
  - about.md

style: dark
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
