title: "Allocated Resources"
description: ""
baseurl: "/"

header_pages:
  - index.md
  - support.md
  - about.md

style: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
theme: jekyll-theme-console
